parameters:
- name: version
  displayName: 'Specify build platform version'
  type: string
  default: "current"
- name: appVersion
  displayName: 'Specify build app version'
  type: string
  default: "18.0"
- name: azureSubscription
  displayName: 'Specify azure subscription name'
  type: string
  default: 'My Azure Service Connection'
- name: createRuntimePackages
  displayName: 'Specify boolean value for runtime package creation'
  type: boolean
  default: True
- name: configurationFilePath
  displayName: 'Specifies the path to the build-settings.json file'
  type: string
  default: '.azureDevOps\build-settings.json'

stages:
- stage: Build
  jobs:
  - job: Build
    timeoutInMinutes: 120
    cancelTimeoutInMinutes: 10
    variables:      
      build.clean: all
      platform: x64
      appBuild: $[counter(variables['appVersion'],0)]
      appRevision: 0
      skipComponentGovernanceDetection: True

    steps:
    - checkout: self
      clean: true
      path: 's'

    - checkout: Template
      clean: false
      path: 's\bcbuildtemplate'

    - task: PowerShell@2
      displayName: 'Copy Build Template'
      inputs:
        targetType: filePath
        filePath: 'bcbuildtemplate\scripts\Copy-Template.ps1'
        arguments: '-AgentToolsDirectory "$(Agent.ToolsDirectory)"'
        failOnStderr: true

    - task: PowerShell@2
      displayName: 'Reading Settings'
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Read-Settings.ps1'
        arguments: '-configurationFilePath "$(Build.Repository.LocalPath)\${{ parameters.configurationFilePath }}" -appVersion "${{ parameters.appVersion }}.$(appBuild).$(appRevision)" -version ${{ parameters.version }} -branchName "$(Build.SourceBranch)"'
        failOnStderr: true
    
    - task: PowerShell@2
      displayName: 'Install bccontainerhelper'
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Install-bccontainerhelper.ps1'
        failOnStderr: true
        
    - task: PowerShell@2
      displayName: 'Create Build Container'
      env:
        Password: $(Password)
        LicenseFile: $(LicenseFile)
        InsiderSasToken: $(InsiderSasToken)
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Create-Container.ps1'
        arguments: '-configurationFilePath "$(Build.Repository.LocalPath)\${{ parameters.configurationFilePath }}"'
        failOnStderr: true

    - task: PowerShell@2
      displayName: 'Compile App'
      env:
        Password: $(Password)
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Compile-App.ps1'
        arguments: '-appFolders "$(appFolders)" -appVersion "${{ parameters.appVersion }}.$(appBuild).$(appRevision)"'
        failOnStderr: true
    
    - task: PowerShell@2
      displayName: 'Compile Test App'
      condition: and(succeeded(),ne(variables['testFolders'],''))
      env:
        Password: $(Password)
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Compile-App.ps1'
        arguments: '-appFolders "$(testFolders)" -appVersion "${{ parameters.appVersion }}.$(appBuild).$(appRevision)"'
        failOnStderr: true
    
    - task: PowerShell@2
      displayName: 'Sign App'
      condition: and(succeeded(),ne(variables['CodeSignPfxFile'],''),ne(variables['CodeSignPfxPassword'],''))
      env:
        codeSignPfxFile: $(CodeSignPfxFile)
        codeSignPfxPassword: $(CodeSignPfxPassword)
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Sign-App.ps1'
        arguments: '-appFolders "$(appFolders)"'
        failOnStderr: true
    
    - task: PowerShell@2
      displayName: 'Publish App'
      env:
        LicenseFile: $(LicenseFile)
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Publish-App.ps1'
        arguments: '-appFolders "$(appFolders)" -skipVerification:([String]::IsNullOrEmpty($CodeSignPfxPassword)) -licenseFile "$(LicenseFile)"'
        failOnStderr: true
    
    - task: PowerShell@2
      displayName: 'Publish Test App using Test License File'
      condition: and(succeeded(),ne(variables['testFolders'],''),ne(variables['TestLicenseFile'],''))
      env:
        LicenseFile: $(TestLicenseFile)
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Publish-App.ps1'
        arguments: '-appFolders "$(testFolders)" -skipVerification -licenseFile "$(TestLicenseFile)"'
        failOnStderr: true

    - task: PowerShell@2
      displayName: 'Publish Test App using Build License File'
      condition: and(succeeded(),ne(variables['testFolders'],''),eq(variables['TestLicenseFile'],''))
      env:
        LicenseFile: $(LicenseFile)
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Publish-App.ps1'
        arguments: '-appFolders "$(testFolders)" -skipVerification -licenseFile "$(LicenseFile)"'
        failOnStderr: true

    - task: PowerShell@2
      displayName: 'Set Test Secret'
      condition: and(succeeded(),ne(variables['TestSecret'],''))
      env:
        TestSecret: $(TestSecret)
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Set-TestSecret.ps1'
        failOnStderr: true

    - task: PowerShell@2
      displayName: 'Run Tests'
      condition: and(succeeded(),ne(variables['testFolders'],''))
      env:
        Password: $(Password)
        TestParameters: $(TestParameters)
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Run-Tests.ps1'
        arguments: '-configurationFilePath "$(Build.Repository.LocalPath)\${{ parameters.configurationFilePath }}" -appFolders "$(testFolders)"'
        failOnStderr: true
      
    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      condition: and(succeeded(),ne(variables['testFolders'],''))
      inputs:
        testResultsFormat: XUnit
        testResultsFiles: TestResults.xml
        failTaskOnFailedTests: true
    
    - task: PowerShell@2
      displayName: 'Get App RuntimePackage'
      condition: and(succeeded(),eq('${{ parameters.createRuntimePackages}}','True'))
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Get-AppRuntimePackage.ps1'
        arguments: '-appFolders "$(appFolders)" -appVersion "${{ parameters.appVersion }}.$(appBuild).$(appRevision)"'
        failOnStderr: true

    - task: PowerShell@2
      displayName: 'Sign RuntimePackage'
      condition: and(succeeded(),eq('${{ parameters.createRuntimePackages}}','True'),ne(variables['CodeSignPfxFile'],''),ne(variables['CodeSignPfxPassword'],''))
      env:
        codeSignPfxFile: $(CodeSignPfxFile)
        codeSignPfxPassword: $(CodeSignPfxPassword)
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Sign-App.ps1'
        arguments: '-appFolders "$(appFolders)" -buildArtifactFolder "$(Build.ArtifactStagingDirectory)\RuntimePackages"'
        failOnStderr: true
        
    - task: PowerShell@1
      displayName: Remove Test App from Artifact Staging Directory
      condition: and(succeeded(),ne(variables['testFolders'],''))
      inputs:
        scriptType: inlineScript
        inlineScript: >
          foreach ($folder in ('$(testFolders)'.Split(','))) {
            Remove-Item (Join-Path '$(Build.ArtifactStagingDirectory)' $folder) -Recurse -Force
          }

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '${{ parameters.appVersion }}'

    - task: PowerShell@2
      displayName: Copy App to Release folder
      condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest'),ne(variables['azureStorageAccount'],''),ne(variables['appFolders'],''))
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\CopyTo-LatestFolder.ps1'
        arguments: '-appFolders "$(appFolders)" -buildArtifactFolder "$(Build.ArtifactStagingDirectory)"  -releaseFolder "${{ parameters.version }}\${{ parameters.appVersion }}"'
        failOnStderr: true              

    - task: AzureFileCopy@4
      displayName: 'Copy Release Apps to Azure Blob'
      condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest'),ne(variables['azureStorageAccount'],''),ne(variables['appFolders'],''))
      inputs:
        SourcePath: '$(Build.ArtifactStagingDirectory)\${{ parameters.version }}\${{ parameters.appVersion }}\*\*.app'
        azureSubscription: '${{ parameters.azureSubscription }}'
        Destination: AzureBlob
        storage: '$(azureStorageAccount)'
        ContainerName: '$(azureContainerName)'
        BlobPrefix: '$(Build.Repository.Name)\$(Build.SourceBranchName)\${{ parameters.appVersion }}\${{ parameters.version }}'

    - task: AzureFileCopy@4
      displayName: 'Copy Artifact Apps to Azure Blob'
      condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest'),eq('${{ parameters.version }}','current'),ne(variables['azureStorageAccount'],''),ne(variables['appFolders'],''))
      inputs:
        SourcePath: '$(Build.ArtifactStagingDirectory)\*\*.app'
        azureSubscription: '${{ parameters.azureSubscription }}'
        Destination: AzureBlob
        storage: '$(azureStorageAccount)'
        ContainerName: '$(azureContainerName)'
        BlobPrefix: 'Artifact\$(Build.Repository.Name)'

    - task: AzureFileCopy@4
      displayName: 'Copy Runtime Apps to Azure Blob'
      condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest'),eq('${{ parameters.createRuntimePackages}}','True'),eq('${{ parameters.version }}','current'),ne(variables['azureStorageAccount'],''),ne(variables['appFolders'],''))
      inputs:
        SourcePath: '$(Build.ArtifactStagingDirectory)\RuntimePackages\*\*.app'
        azureSubscription: '${{ parameters.azureSubscription }}'
        Destination: AzureBlob
        storage: '$(azureStorageAccount)'
        ContainerName: '$(azureContainerName)'
        BlobPrefix: 'Runtime\$(Build.Repository.Name)'

    - task: PowerShell@2
      displayName: 'Remove Build Container'
      condition: ne(variables['reuseContainer'],'True')
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Remove-Container.ps1'

    - task: PowerShell@2
      displayName: 'Remove Unused Container Image'
      condition: and(ne(variables['Agent.Name'],'Hosted Agent'),ne(variables['Agent.Name'],'Azure Pipelines*'))
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Remove-OldDockerImages.ps1'

    - task: PowerShell@2
      displayName: 'Validate App'
      condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest'),eq('${{ parameters.version }}','current'))
      env:
        LicenseFile: $(LicenseFile)
        InsiderSasToken: $(InsiderSasToken)
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Validate-App.ps1'
        arguments: '-configurationFilePath "$(Build.Repository.LocalPath)\${{ parameters.configurationFilePath }}" -artifactsFolder "$(Build.ArtifactStagingDirectory)" -branchName "$(Build.SourceBranch)" -version ${{ parameters.version }}'
        failOnStderr: true    

    - task: PowerShell@2
      displayName: 'Upgrade Microsoft Apps'
      condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest'),eq('${{ parameters.version }}','current'))
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Upgrade-MicrosoftApps.ps1'
        arguments: '-configurationFilePath "$(Build.Repository.LocalPath)\${{ parameters.configurationFilePath }}" -branchName "$(Build.SourceBranch)"'
        failOnStderr: true

    - task: PowerShell@2
      displayName: 'Deploy to Environment'
      condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest'),eq('${{ parameters.version }}','current'))
      env:
        ClientId: $(ClientId)
        ClientSecret: $(ClientSecret)
        PowerShellUsername: $(PowerShellUsername)
        PowerShellPassword: $(PowerShellPassword)
      inputs:
        targetType: filePath
        filePath: '$(Agent.ToolsDirectory)\bcbuildtemplate\Deploy-App.ps1'
        arguments: '-configurationFilePath "$(Build.Repository.LocalPath)\${{ parameters.configurationFilePath }}" -artifactsFolder "$(Build.ArtifactStagingDirectory)" -branchName "$(Build.SourceBranch)"'
        failOnStderr: true
